<?php

defined('BASEPATH') or exit('No direct script access allowed');

class Zatca extends AdminController
{
    public function __construct()
    {
        parent::__construct();
        if (!has_permission('zatca', '', 'view')) {
            access_denied('ZATCA E-Invoicing');
        }
    }

    public function index()
    {
        redirect(admin_url('zatca/history'));
    }

    public function settings()
    {
        if ($this->input->post()) {
            if (!has_permission('zatca', '', 'edit')) {
                access_denied('ZATCA Settings');
            }
            
            $data = $this->input->post();
            
            // Save standard options
            foreach ($data as $key => $value) {
                if (strpos($key, 'zatca_') !== false) {
                     update_option($key, $value);
                }
            }
            
            set_alert('success', _l('updated_successfully', _l('settings')));
            redirect(admin_url('zatca/settings'));
        }

        $data['title'] = _l('zatca_settings');
        $this->load->view('settings', $data);
    }

    public function history()
    {
        // $this->load->model('zatca_model');
        $data['title'] = _l('zatca_history');
        // $data['logs'] = $this->zatca_model->get_logs();
        $this->load->view('history', $data);
    }
    
    public function generate_keys() 
    {
        if (!has_permission('zatca', '', 'create')) {
             access_denied('ZATCA CSR Generation');
        }

        $this->load->library('zatca/zatca_invoice');
        
        $data = [
            'common_name' => get_option('zatca_csr_common_name') ? get_option('zatca_csr_common_name') : 'TST-886431145-0000',
            'organization_unit' => 'IT',
            'organization_name' => get_option('invoice_company_name'),
            'country_name' => 'SA',
            'vat_number' => get_option('company_vat'),
            'address' => get_option('invoice_company_address')
        ];
        
        // Basic validation
        if(empty($data['common_name']) || empty($data['organization_name'])) {
            set_alert('warning', 'Please configure Company Name and Common Name first.');
            redirect(admin_url('zatca/settings'));
        }

        $csr = $this->zatca_invoice->generate_csr($data);
        
        if ($csr) {
            // Save CSR temporarily or just to show it? Use options for now.
            // In real flow, we send this CSR to ZATCA immediately.
            // For now, let's verify it generated by saving it log or option
            update_option('zatca_last_generated_csr', $csr);
            set_alert('success', _l('zatca_csr_generated'));
        } else {
            set_alert('danger', 'CSR Generation Failed. Check logs.');
        }
        
        redirect(admin_url('zatca/settings'));
    }

    public function onboard()
    {
        if (!has_permission('zatca', '', 'create')) {
             access_denied('ZATCA Onboarding');
        }

        $otp = get_option('zatca_otp');
        // CSR should be generated previously
        // Ideally we regenerate CSR or use the one from "last_generated_csr" if we saved it, 
        // OR re-generate it on the fly using the keys we have.
        // Let's assume we re-generate or retrieve. Since we didn't save the full CSR to a file, let's re-generate.
        
        $this->load->library('zatca/zatca_invoice');
        $this->load->library('zatca/zatca_api');
        
        $data = [
            'common_name' => get_option('zatca_csr_common_name'),
            'organization_unit' => 'IT',
            'organization_name' => get_option('invoice_company_name'),
            'country_name' => 'SA',
            'vat_number' => get_option('company_vat'),
            'address' => get_option('invoice_company_address')
        ];
        
        // Re-generate CSR with existing keys 
        $csr = $this->zatca_invoice->generate_csr($data);
        
        if(!$csr || empty($otp)){
            set_alert('warning', 'CSR or OTP missing.');
            redirect(admin_url('zatca/settings'));
        }
        
        // 1. Get Compliance CSID
        $response = $this->zatca_api->issue_compliance_certificate($csr, $otp);
        
        if($response['code'] == 200 || $response['code'] == 201 || $response['code'] == 202){
            $json = $response['response'];
            
            // Save Compliance Credentials
            update_option('zatca_compliance_csid', $json['binarySecurityToken']);
            update_option('zatca_compliance_secret', $json['secret']);
            update_option('zatca_compliance_request_id', $json['requestID']);
            
            set_alert('success', _l('zatca_onboard_success') . ' (Compliance)');
            
            // PENDING: If Production Mode, we might want to auto-request Production CSID here.
            // For now, let's stop at Compliance as that's safe for first pass.
            
        } else {
            set_alert('danger', _l('zatca_onboard_failed') . ': ' . print_r($response['response'], true));
        }
        
        redirect(admin_url('zatca/settings'));
    }
}
